Content:
    vtb:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: vtb
        repo: https://github.com/idaholab/virtual_test_bed
        menu:
            Contributing: contributing.md
            Citing: citing.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        #hide:
        #    framework: !include ${MOOSE_DIR}/framework/doc/hidden.yml
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - include
    MooseDocs.extensions.acronym:
        acronyms:
            moose: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
            vtb: !include ${ROOT_DIR}/doc/acronyms.yml
